spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

project:
    poster: posters/